/*
###############################################################
#  Generated by:      Cadence Innovus 20.14-s095_1
#  OS:                Linux x86_64(Host ID capcad45)
#  Generated on:      Tue Sep 16 13:28:04 2025
#  Design:            apb_timer
#  Command:           saveNetlist apb_timer.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Sep 16 2025 09:43:40 IST (Sep 16 2025 04:13:40 UTC)
// Verification Directory fv/apb_timer 
module apb_timer (
	PCLK, 
	PCLKG, 
	PRESETn, 
	PSEL, 
	PADDR, 
	PENABLE, 
	PWRITE, 
	PWDATA, 
	ECOREVNUM, 
	PRDATA, 
	PREADY, 
	PSLVERR, 
	EXTIN, 
	TIMERINT);
   input PCLK;
   input PCLKG;
   input PRESETn;
   input PSEL;
   input [11:2] PADDR;
   input PENABLE;
   input PWRITE;
   input [31:0] PWDATA;
   input [3:0] ECOREVNUM;
   output [31:0] PRDATA;
   output PREADY;
   output PSLVERR;
   input EXTIN;
   output TIMERINT;

   // Internal wires
   wire FE_OFN4_PRESETn;
   wire FE_OFN3_n_4;
   wire FE_OFN2_n;
   wire [7:0] read_mux_byte0_reg;
   wire [31:0] reg_curr_val;
   wire [31:0] reg_reload_val;
   wire [3:0] reg_ctrl;
   wire dec_sub_440_29_n_325;
   wire dec_sub_440_29_n_335;
   wire dec_sub_440_29_n_338;
   wire dec_sub_440_29_n_349;
   wire dec_sub_440_29_n_354;
   wire dec_sub_440_29_n_357;
   wire dec_sub_440_29_n_358;
   wire dec_sub_440_29_n_368;
   wire dec_sub_440_29_n_370;
   wire dec_sub_440_29_n_373;
   wire dec_sub_440_29_n_376;
   wire dec_sub_440_29_n_382;
   wire dec_sub_440_29_n_386;
   wire dec_sub_440_29_n_388;
   wire dec_sub_440_29_n_390;
   wire dec_sub_440_29_n_396;
   wire dec_sub_440_29_n_398;
   wire dec_sub_440_29_n_400;
   wire dec_sub_440_29_n_402;
   wire dec_sub_440_29_n_404;
   wire dec_sub_440_29_n_409;
   wire dec_sub_440_29_n_412;
   wire dec_sub_440_29_n_415;
   wire dec_sub_440_29_n_418;
   wire dec_sub_440_29_n_420;
   wire dec_sub_440_29_n_421;
   wire dec_sub_440_29_n_424;
   wire dec_sub_440_29_n_426;
   wire dec_sub_440_29_n_429;
   wire dec_sub_440_29_n_434;
   wire dec_sub_440_29_n_437;
   wire dec_sub_440_29_n_441;
   wire dec_sub_440_29_n_443;
   wire dec_sub_440_29_n_446;
   wire dec_sub_440_29_n_447;
   wire dec_sub_440_29_n_449;
   wire dec_sub_440_29_n_450;
   wire dec_sub_440_29_n_452;
   wire dec_sub_440_29_n_454;
   wire dec_sub_440_29_n_455;
   wire dec_sub_440_29_n_457;
   wire ext_in_delay;
   wire ext_in_sync1;
   wire ext_in_sync2;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_179;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_195;
   wire n_196;
   wire n_197;
   wire n_198;
   wire n_199;
   wire n_200;
   wire n_201;
   wire n_202;
   wire n_203;
   wire n_204;
   wire n_205;
   wire n_206;
   wire n_207;
   wire n_208;
   wire n_209;
   wire n_210;
   wire n_211;
   wire n_212;
   wire n_213;
   wire n_214;
   wire n_215;
   wire n_216;
   wire n_302;
   wire read_enable;

   assign PSLVERR = 1'b0 ;
   assign PREADY = 1'b1 ;

   BUFX2 FE_OFC5_PRESETn (.A(PRESETn),
	.Y(FE_OFN4_PRESETn));
   INVX2 FE_OFC4_n_4 (.A(n_185),
	.Y(FE_OFN3_n_4));
   INVX1 FE_OFC3_n_4 (.A(n_4),
	.Y(n_185));
   INVX1 FE_OFC2_0 (.A(n_31),
	.Y(FE_OFN2_n));
   INVX1 FE_OFC0_0 (.A(n_0),
	.Y(n_31));
   INVX1 g3796 (.A(n_181),
	.Y(n_179));
   AO22X4 g4442__2398 (.A0(read_mux_byte0_reg[5]),
	.A1(n_178),
	.B0(reg_curr_val[5]),
	.B1(n_172),
	.Y(PRDATA[5]));
   AO22X4 g4443__5107 (.A0(read_mux_byte0_reg[6]),
	.A1(n_178),
	.B0(reg_curr_val[6]),
	.B1(n_172),
	.Y(PRDATA[6]));
   AO22X4 g4444__6260 (.A0(read_mux_byte0_reg[7]),
	.A1(n_178),
	.B0(reg_curr_val[7]),
	.B1(n_172),
	.Y(PRDATA[7]));
   AO22X4 g4445__4319 (.A0(read_mux_byte0_reg[4]),
	.A1(n_178),
	.B0(reg_curr_val[4]),
	.B1(n_172),
	.Y(PRDATA[4]));
   AO22X4 g4446__8428 (.A0(read_mux_byte0_reg[1]),
	.A1(n_178),
	.B0(reg_curr_val[1]),
	.B1(n_172),
	.Y(PRDATA[1]));
   AO22X4 g4447__5526 (.A0(read_mux_byte0_reg[2]),
	.A1(n_178),
	.B0(reg_curr_val[2]),
	.B1(n_172),
	.Y(PRDATA[2]));
   AO22X4 g4448__6783 (.A0(read_mux_byte0_reg[3]),
	.A1(n_178),
	.B0(reg_curr_val[3]),
	.B1(n_172),
	.Y(PRDATA[3]));
   AO22X4 g4449__3680 (.A0(read_mux_byte0_reg[0]),
	.A1(n_178),
	.B0(reg_curr_val[0]),
	.B1(n_172),
	.Y(PRDATA[0]));
   AO22X4 g4450__1617 (.A0(reg_reload_val[31]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[31]),
	.B1(n_172),
	.Y(PRDATA[31]));
   AO22X4 g4451__2802 (.A0(reg_reload_val[10]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[10]),
	.B1(n_172),
	.Y(PRDATA[10]));
   AO22X4 g4452__1705 (.A0(reg_reload_val[9]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[9]),
	.B1(n_172),
	.Y(PRDATA[9]));
   AO22X4 g4453__5122 (.A0(reg_reload_val[8]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[8]),
	.B1(n_172),
	.Y(PRDATA[8]));
   AO22X4 g4454__8246 (.A0(reg_reload_val[23]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[23]),
	.B1(n_172),
	.Y(PRDATA[23]));
   AO22X4 g4455__7098 (.A0(reg_reload_val[21]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[21]),
	.B1(n_172),
	.Y(PRDATA[21]));
   AO22X4 g4456__6131 (.A0(reg_reload_val[22]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[22]),
	.B1(n_172),
	.Y(PRDATA[22]));
   AO22X4 g4457__1881 (.A0(reg_reload_val[29]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[29]),
	.B1(n_172),
	.Y(PRDATA[29]));
   AO22X4 g4458__5115 (.A0(reg_reload_val[28]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[28]),
	.B1(n_172),
	.Y(PRDATA[28]));
   AO22X4 g4459__7482 (.A0(reg_reload_val[20]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[20]),
	.B1(n_172),
	.Y(PRDATA[20]));
   AO22X4 g4460__4733 (.A0(reg_reload_val[19]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[19]),
	.B1(n_172),
	.Y(PRDATA[19]));
   AO22X4 g4461__6161 (.A0(reg_reload_val[27]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[27]),
	.B1(n_172),
	.Y(PRDATA[27]));
   AO22X4 g4462__9315 (.A0(reg_reload_val[14]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[14]),
	.B1(n_172),
	.Y(PRDATA[14]));
   AO22X4 g4463__9945 (.A0(reg_reload_val[30]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[30]),
	.B1(n_172),
	.Y(PRDATA[30]));
   AO22X4 g4464__2883 (.A0(reg_reload_val[26]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[26]),
	.B1(n_172),
	.Y(PRDATA[26]));
   AO22X4 g4465__2346 (.A0(reg_reload_val[17]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[17]),
	.B1(n_172),
	.Y(PRDATA[17]));
   AO22X4 g4466__1666 (.A0(reg_reload_val[16]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[16]),
	.B1(n_172),
	.Y(PRDATA[16]));
   AO22X4 g4467__7410 (.A0(reg_reload_val[15]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[15]),
	.B1(n_172),
	.Y(PRDATA[15]));
   AO22X4 g4468__6417 (.A0(reg_reload_val[18]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[18]),
	.B1(n_172),
	.Y(PRDATA[18]));
   AO22X4 g4469__5477 (.A0(reg_reload_val[25]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[25]),
	.B1(n_172),
	.Y(PRDATA[25]));
   AO22X4 g4470__2398 (.A0(reg_reload_val[13]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[13]),
	.B1(n_172),
	.Y(PRDATA[13]));
   AO22X4 g4471__5107 (.A0(reg_reload_val[24]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[24]),
	.B1(n_172),
	.Y(PRDATA[24]));
   AO22X4 g4472__6260 (.A0(reg_reload_val[12]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[12]),
	.B1(n_172),
	.Y(PRDATA[12]));
   AO22X4 g4473__4319 (.A0(reg_reload_val[11]),
	.A1(FE_OFN3_n_4),
	.B0(reg_curr_val[11]),
	.B1(n_172),
	.Y(PRDATA[11]));
   AO22XL g4474__8428 (.A0(n_182),
	.A1(n_177),
	.B0(n_175),
	.B1(n_183),
	.Y(n_178));
   INVX1 g4478 (.A(n_177),
	.Y(n_184));
   NOR2XL g4479__5526 (.A(read_enable),
	.B(n_183),
	.Y(n_177));
   OR4X1 g4480__6783 (.A(PADDR[4]),
	.B(PADDR[5]),
	.C(n_174),
	.D(n_176),
	.Y(n_183));
   OR4X1 g4481__3680 (.A(PADDR[8]),
	.B(PADDR[9]),
	.C(PADDR[10]),
	.D(PADDR[11]),
	.Y(n_176));
   INVX1 g4482 (.A(read_enable),
	.Y(n_175));
   OR2X1 g4483__1617 (.A(PADDR[7]),
	.B(PADDR[6]),
	.Y(n_174));
   NAND2BX1 g4487__2802 (.AN(PADDR[2]),
	.B(PADDR[3]),
	.Y(n_181));
   NAND2BX1 g4488__1705 (.AN(PADDR[3]),
	.B(PADDR[2]),
	.Y(n_182));
   NOR2BX1 g2__5122 (.AN(n_177),
	.B(n_181),
	.Y(n_4));
   NOR2BX4 g4490__8246 (.AN(n_177),
	.B(n_182),
	.Y(n_172));
   NAND2BX1 g4491__7098 (.AN(PWRITE),
	.B(PSEL),
	.Y(read_enable));
   SDFFRHQX1 ext_in_delay_reg (.CK(PCLK),
	.D(ext_in_sync2),
	.Q(ext_in_delay),
	.RN(PRESETn),
	.SE(n_18),
	.SI(ext_in_delay));
   SDFFRHQX1 ext_in_sync1_reg (.CK(PCLK),
	.D(EXTIN),
	.Q(ext_in_sync1),
	.RN(PRESETn),
	.SE(n_18),
	.SI(ext_in_sync1));
   DFFRHQX2 \read_mux_byte0_reg_reg[0]  (.CK(PCLKG),
	.D(n_56),
	.Q(read_mux_byte0_reg[0]),
	.RN(PRESETn));
   DFFRHQX2 \read_mux_byte0_reg_reg[1]  (.CK(PCLKG),
	.D(n_57),
	.Q(read_mux_byte0_reg[1]),
	.RN(PRESETn));
   DFFRHQX2 \read_mux_byte0_reg_reg[2]  (.CK(PCLKG),
	.D(n_58),
	.Q(read_mux_byte0_reg[2]),
	.RN(PRESETn));
   DFFRHQX2 \read_mux_byte0_reg_reg[3]  (.CK(PCLKG),
	.D(n_60),
	.Q(read_mux_byte0_reg[3]),
	.RN(PRESETn));
   DFFRHQX2 \read_mux_byte0_reg_reg[4]  (.CK(PCLKG),
	.D(n_61),
	.Q(read_mux_byte0_reg[4]),
	.RN(FE_OFN4_PRESETn));
   DFFRHQX2 \read_mux_byte0_reg_reg[5]  (.CK(PCLKG),
	.D(n_59),
	.Q(read_mux_byte0_reg[5]),
	.RN(FE_OFN4_PRESETn));
   DFFRHQX2 \read_mux_byte0_reg_reg[6]  (.CK(PCLKG),
	.D(n_55),
	.Q(read_mux_byte0_reg[6]),
	.RN(FE_OFN4_PRESETn));
   DFFRHQX2 \read_mux_byte0_reg_reg[7]  (.CK(PCLKG),
	.D(n_54),
	.Q(read_mux_byte0_reg[7]),
	.RN(FE_OFN4_PRESETn));
   SDFFRHQX1 \reg_ctrl_reg[0]  (.CK(PCLKG),
	.D(PWDATA[0]),
	.Q(reg_ctrl[0]),
	.RN(PRESETn),
	.SE(n_32),
	.SI(reg_ctrl[0]));
   SDFFRHQX1 \reg_ctrl_reg[1]  (.CK(PCLKG),
	.D(PWDATA[1]),
	.Q(reg_ctrl[1]),
	.RN(PRESETn),
	.SE(n_32),
	.SI(reg_ctrl[1]));
   SDFFRHQX1 \reg_ctrl_reg[2]  (.CK(PCLKG),
	.D(PWDATA[2]),
	.Q(reg_ctrl[2]),
	.RN(PRESETn),
	.SE(n_32),
	.SI(reg_ctrl[2]));
   SDFFRHQX1 \reg_ctrl_reg[3]  (.CK(PCLKG),
	.D(PWDATA[3]),
	.Q(reg_ctrl[3]),
	.RN(PRESETn),
	.SE(n_32),
	.SI(reg_ctrl[3]));
   DFFRHQX2 \reg_curr_val_reg[0]  (.CK(PCLK),
	.D(n_140),
	.Q(reg_curr_val[0]),
	.RN(PRESETn));
   DFFRHQX2 \reg_curr_val_reg[1]  (.CK(PCLK),
	.D(n_157),
	.Q(reg_curr_val[1]),
	.RN(PRESETn));
   DFFRHQX2 \reg_curr_val_reg[2]  (.CK(PCLK),
	.D(n_160),
	.Q(reg_curr_val[2]),
	.RN(PRESETn));
   DFFRHQX2 \reg_curr_val_reg[3]  (.CK(PCLK),
	.D(n_159),
	.Q(reg_curr_val[3]),
	.RN(PRESETn));
   DFFRHQX2 \reg_curr_val_reg[4]  (.CK(PCLK),
	.D(n_158),
	.Q(reg_curr_val[4]),
	.RN(PRESETn));
   DFFRHQX2 \reg_curr_val_reg[5]  (.CK(PCLK),
	.D(n_171),
	.Q(reg_curr_val[5]),
	.RN(FE_OFN4_PRESETn));
   DFFRHQX2 \reg_curr_val_reg[6]  (.CK(PCLK),
	.D(n_154),
	.Q(reg_curr_val[6]),
	.RN(FE_OFN4_PRESETn));
   DFFRHQX2 \reg_curr_val_reg[7]  (.CK(PCLK),
	.D(n_156),
	.Q(reg_curr_val[7]),
	.RN(FE_OFN4_PRESETn));
   DFFRHQX2 \reg_curr_val_reg[8]  (.CK(PCLK),
	.D(n_155),
	.Q(reg_curr_val[8]),
	.RN(FE_OFN4_PRESETn));
   DFFRHQX2 \reg_curr_val_reg[9]  (.CK(PCLK),
	.D(n_153),
	.Q(reg_curr_val[9]),
	.RN(FE_OFN4_PRESETn));
   DFFRHQX2 \reg_curr_val_reg[10]  (.CK(PCLK),
	.D(n_152),
	.Q(reg_curr_val[10]),
	.RN(FE_OFN4_PRESETn));
   DFFRHQX2 \reg_curr_val_reg[11]  (.CK(PCLK),
	.D(n_151),
	.Q(reg_curr_val[11]),
	.RN(FE_OFN4_PRESETn));
   DFFRHQX2 \reg_curr_val_reg[12]  (.CK(PCLK),
	.D(n_150),
	.Q(reg_curr_val[12]),
	.RN(FE_OFN4_PRESETn));
   DFFRHQX2 \reg_curr_val_reg[13]  (.CK(PCLK),
	.D(n_149),
	.Q(reg_curr_val[13]),
	.RN(FE_OFN4_PRESETn));
   DFFRHQX2 \reg_curr_val_reg[14]  (.CK(PCLK),
	.D(n_148),
	.Q(reg_curr_val[14]),
	.RN(FE_OFN4_PRESETn));
   DFFRHQX2 \reg_curr_val_reg[15]  (.CK(PCLK),
	.D(n_147),
	.Q(reg_curr_val[15]),
	.RN(FE_OFN4_PRESETn));
   DFFRHQX2 \reg_curr_val_reg[16]  (.CK(PCLK),
	.D(n_146),
	.Q(reg_curr_val[16]),
	.RN(FE_OFN4_PRESETn));
   DFFRHQX2 \reg_curr_val_reg[17]  (.CK(PCLK),
	.D(n_145),
	.Q(reg_curr_val[17]),
	.RN(FE_OFN4_PRESETn));
   DFFRHQX2 \reg_curr_val_reg[18]  (.CK(PCLK),
	.D(n_144),
	.Q(reg_curr_val[18]),
	.RN(FE_OFN4_PRESETn));
   DFFRHQX2 \reg_curr_val_reg[19]  (.CK(PCLK),
	.D(n_143),
	.Q(reg_curr_val[19]),
	.RN(FE_OFN4_PRESETn));
   DFFRHQX2 \reg_curr_val_reg[20]  (.CK(PCLK),
	.D(n_142),
	.Q(reg_curr_val[20]),
	.RN(PRESETn));
   DFFRHQX2 \reg_curr_val_reg[21]  (.CK(PCLK),
	.D(n_141),
	.Q(reg_curr_val[21]),
	.RN(PRESETn));
   DFFRHQX2 \reg_curr_val_reg[22]  (.CK(PCLK),
	.D(n_168),
	.Q(reg_curr_val[22]),
	.RN(PRESETn));
   DFFRHQX2 \reg_curr_val_reg[23]  (.CK(PCLK),
	.D(n_170),
	.Q(reg_curr_val[23]),
	.RN(PRESETn));
   DFFRHQX2 \reg_curr_val_reg[24]  (.CK(PCLK),
	.D(n_169),
	.Q(reg_curr_val[24]),
	.RN(PRESETn));
   DFFRHQX2 \reg_curr_val_reg[25]  (.CK(PCLK),
	.D(n_167),
	.Q(reg_curr_val[25]),
	.RN(PRESETn));
   DFFRHQX2 \reg_curr_val_reg[26]  (.CK(PCLK),
	.D(n_166),
	.Q(reg_curr_val[26]),
	.RN(PRESETn));
   DFFRHQX2 \reg_curr_val_reg[27]  (.CK(PCLK),
	.D(n_165),
	.Q(reg_curr_val[27]),
	.RN(PRESETn));
   DFFRHQX2 \reg_curr_val_reg[28]  (.CK(PCLK),
	.D(n_164),
	.Q(reg_curr_val[28]),
	.RN(PRESETn));
   DFFRHQX2 \reg_curr_val_reg[29]  (.CK(PCLK),
	.D(n_163),
	.Q(reg_curr_val[29]),
	.RN(PRESETn));
   DFFRHQX2 \reg_curr_val_reg[30]  (.CK(PCLK),
	.D(n_162),
	.Q(reg_curr_val[30]),
	.RN(PRESETn));
   DFFRHQX2 \reg_curr_val_reg[31]  (.CK(PCLK),
	.D(n_161),
	.Q(reg_curr_val[31]),
	.RN(PRESETn));
   SDFFRHQX1 \reg_reload_val_reg[1]  (.CK(PCLKG),
	.D(reg_reload_val[1]),
	.Q(reg_reload_val[1]),
	.RN(PRESETn),
	.SE(n_30),
	.SI(PWDATA[1]));
   SDFFRHQX1 \reg_reload_val_reg[2]  (.CK(PCLKG),
	.D(reg_reload_val[2]),
	.Q(reg_reload_val[2]),
	.RN(PRESETn),
	.SE(n_30),
	.SI(PWDATA[2]));
   SDFFRHQX1 \reg_reload_val_reg[3]  (.CK(PCLKG),
	.D(reg_reload_val[3]),
	.Q(reg_reload_val[3]),
	.RN(PRESETn),
	.SE(n_30),
	.SI(PWDATA[3]));
   SDFFRHQX1 \reg_reload_val_reg[4]  (.CK(PCLKG),
	.D(reg_reload_val[4]),
	.Q(reg_reload_val[4]),
	.RN(PRESETn),
	.SE(n_30),
	.SI(PWDATA[4]));
   SDFFRHQX1 \reg_reload_val_reg[5]  (.CK(PCLKG),
	.D(reg_reload_val[5]),
	.Q(reg_reload_val[5]),
	.RN(PRESETn),
	.SE(n_30),
	.SI(PWDATA[5]));
   SDFFRHQX1 \reg_reload_val_reg[6]  (.CK(PCLKG),
	.D(reg_reload_val[6]),
	.Q(reg_reload_val[6]),
	.RN(FE_OFN4_PRESETn),
	.SE(n_30),
	.SI(PWDATA[6]));
   SDFFRHQX1 \reg_reload_val_reg[7]  (.CK(PCLKG),
	.D(reg_reload_val[7]),
	.Q(reg_reload_val[7]),
	.RN(FE_OFN4_PRESETn),
	.SE(n_30),
	.SI(PWDATA[7]));
   SDFFRHQX1 \reg_reload_val_reg[8]  (.CK(PCLKG),
	.D(reg_reload_val[8]),
	.Q(reg_reload_val[8]),
	.RN(FE_OFN4_PRESETn),
	.SE(n_30),
	.SI(PWDATA[8]));
   SDFFRHQX1 \reg_reload_val_reg[9]  (.CK(PCLKG),
	.D(reg_reload_val[9]),
	.Q(reg_reload_val[9]),
	.RN(FE_OFN4_PRESETn),
	.SE(n_30),
	.SI(PWDATA[9]));
   SDFFRHQX1 \reg_reload_val_reg[10]  (.CK(PCLKG),
	.D(reg_reload_val[10]),
	.Q(reg_reload_val[10]),
	.RN(FE_OFN4_PRESETn),
	.SE(n_30),
	.SI(PWDATA[10]));
   SDFFRHQX1 \reg_reload_val_reg[11]  (.CK(PCLKG),
	.D(reg_reload_val[11]),
	.Q(reg_reload_val[11]),
	.RN(FE_OFN4_PRESETn),
	.SE(n_30),
	.SI(PWDATA[11]));
   SDFFRHQX1 \reg_reload_val_reg[12]  (.CK(PCLKG),
	.D(reg_reload_val[12]),
	.Q(reg_reload_val[12]),
	.RN(FE_OFN4_PRESETn),
	.SE(n_30),
	.SI(PWDATA[12]));
   SDFFRHQX1 \reg_reload_val_reg[13]  (.CK(PCLKG),
	.D(reg_reload_val[13]),
	.Q(reg_reload_val[13]),
	.RN(FE_OFN4_PRESETn),
	.SE(n_30),
	.SI(PWDATA[13]));
   SDFFRHQX1 \reg_reload_val_reg[14]  (.CK(PCLKG),
	.D(reg_reload_val[14]),
	.Q(reg_reload_val[14]),
	.RN(FE_OFN4_PRESETn),
	.SE(n_30),
	.SI(PWDATA[14]));
   SDFFRHQX1 \reg_reload_val_reg[15]  (.CK(PCLKG),
	.D(reg_reload_val[15]),
	.Q(reg_reload_val[15]),
	.RN(FE_OFN4_PRESETn),
	.SE(n_30),
	.SI(PWDATA[15]));
   SDFFRHQX1 \reg_reload_val_reg[16]  (.CK(PCLKG),
	.D(reg_reload_val[16]),
	.Q(reg_reload_val[16]),
	.RN(FE_OFN4_PRESETn),
	.SE(n_30),
	.SI(PWDATA[16]));
   SDFFRHQX1 \reg_reload_val_reg[17]  (.CK(PCLKG),
	.D(reg_reload_val[17]),
	.Q(reg_reload_val[17]),
	.RN(FE_OFN4_PRESETn),
	.SE(n_30),
	.SI(PWDATA[17]));
   SDFFRHQX1 \reg_reload_val_reg[18]  (.CK(PCLKG),
	.D(reg_reload_val[18]),
	.Q(reg_reload_val[18]),
	.RN(FE_OFN4_PRESETn),
	.SE(n_30),
	.SI(PWDATA[18]));
   SDFFRHQX1 \reg_reload_val_reg[19]  (.CK(PCLKG),
	.D(reg_reload_val[19]),
	.Q(reg_reload_val[19]),
	.RN(FE_OFN4_PRESETn),
	.SE(n_30),
	.SI(PWDATA[19]));
   SDFFRHQX1 \reg_reload_val_reg[20]  (.CK(PCLKG),
	.D(reg_reload_val[20]),
	.Q(reg_reload_val[20]),
	.RN(PRESETn),
	.SE(n_30),
	.SI(PWDATA[20]));
   SDFFRHQX1 \reg_reload_val_reg[21]  (.CK(PCLKG),
	.D(reg_reload_val[21]),
	.Q(reg_reload_val[21]),
	.RN(PRESETn),
	.SE(n_30),
	.SI(PWDATA[21]));
   SDFFRHQX1 \reg_reload_val_reg[22]  (.CK(PCLKG),
	.D(reg_reload_val[22]),
	.Q(reg_reload_val[22]),
	.RN(FE_OFN4_PRESETn),
	.SE(n_30),
	.SI(PWDATA[22]));
   SDFFRHQX1 \reg_reload_val_reg[23]  (.CK(PCLKG),
	.D(reg_reload_val[23]),
	.Q(reg_reload_val[23]),
	.RN(PRESETn),
	.SE(n_30),
	.SI(PWDATA[23]));
   SDFFRHQX1 \reg_reload_val_reg[24]  (.CK(PCLKG),
	.D(reg_reload_val[24]),
	.Q(reg_reload_val[24]),
	.RN(PRESETn),
	.SE(n_30),
	.SI(PWDATA[24]));
   SDFFRHQX1 \reg_reload_val_reg[25]  (.CK(PCLKG),
	.D(reg_reload_val[25]),
	.Q(reg_reload_val[25]),
	.RN(PRESETn),
	.SE(n_30),
	.SI(PWDATA[25]));
   SDFFRHQX1 \reg_reload_val_reg[26]  (.CK(PCLKG),
	.D(reg_reload_val[26]),
	.Q(reg_reload_val[26]),
	.RN(PRESETn),
	.SE(n_30),
	.SI(PWDATA[26]));
   SDFFRHQX1 \reg_reload_val_reg[27]  (.CK(PCLKG),
	.D(reg_reload_val[27]),
	.Q(reg_reload_val[27]),
	.RN(PRESETn),
	.SE(n_30),
	.SI(PWDATA[27]));
   SDFFRHQX1 \reg_reload_val_reg[28]  (.CK(PCLKG),
	.D(reg_reload_val[28]),
	.Q(reg_reload_val[28]),
	.RN(PRESETn),
	.SE(n_30),
	.SI(PWDATA[28]));
   SDFFRHQX1 \reg_reload_val_reg[29]  (.CK(PCLKG),
	.D(reg_reload_val[29]),
	.Q(reg_reload_val[29]),
	.RN(PRESETn),
	.SE(n_30),
	.SI(PWDATA[29]));
   SDFFRHQX1 \reg_reload_val_reg[30]  (.CK(PCLKG),
	.D(reg_reload_val[30]),
	.Q(reg_reload_val[30]),
	.RN(PRESETn),
	.SE(n_30),
	.SI(PWDATA[30]));
   SDFFRHQX1 \reg_reload_val_reg[31]  (.CK(PCLKG),
	.D(reg_reload_val[31]),
	.Q(reg_reload_val[31]),
	.RN(PRESETn),
	.SE(n_30),
	.SI(PWDATA[31]));
   SDFFRHQX4 reg_timer_int_reg (.CK(PCLK),
	.D(TIMERINT),
	.Q(TIMERINT),
	.RN(PRESETn),
	.SE(n_76),
	.SI(n_72));
   NAND2X1 g7450__6131 (.A(n_109),
	.B(n_110),
	.Y(n_171));
   NAND2X1 g7451__1881 (.A(n_135),
	.B(n_136),
	.Y(n_170));
   NAND2X1 g7452__5115 (.A(n_133),
	.B(n_134),
	.Y(n_169));
   NAND2X1 g7453__7482 (.A(n_138),
	.B(n_137),
	.Y(n_168));
   NAND2X1 g7454__4733 (.A(n_131),
	.B(n_132),
	.Y(n_167));
   NAND2X1 g7455__6161 (.A(n_129),
	.B(n_130),
	.Y(n_166));
   NAND2X1 g7456__9315 (.A(n_127),
	.B(n_128),
	.Y(n_165));
   NAND2X1 g7457__9945 (.A(n_125),
	.B(n_126),
	.Y(n_164));
   NAND2X1 g7458__2883 (.A(n_121),
	.B(n_124),
	.Y(n_163));
   NAND2X1 g7459__2346 (.A(n_122),
	.B(n_123),
	.Y(n_162));
   NAND2X1 g7460__1666 (.A(n_119),
	.B(n_120),
	.Y(n_161));
   NAND2X1 g7461__7410 (.A(n_115),
	.B(n_116),
	.Y(n_160));
   NAND2X1 g7462__6417 (.A(n_113),
	.B(n_114),
	.Y(n_159));
   NAND2X1 g7463__5477 (.A(n_111),
	.B(n_112),
	.Y(n_158));
   NAND2X1 g7464__2398 (.A(n_117),
	.B(n_118),
	.Y(n_157));
   NAND2X1 g7466__5107 (.A(n_105),
	.B(n_106),
	.Y(n_156));
   NAND2X1 g7467__6260 (.A(n_103),
	.B(n_104),
	.Y(n_155));
   NAND2X1 g7468__4319 (.A(n_108),
	.B(n_107),
	.Y(n_154));
   NAND2X1 g7469__8428 (.A(n_101),
	.B(n_102),
	.Y(n_153));
   NAND2X1 g7470__5526 (.A(n_99),
	.B(n_100),
	.Y(n_152));
   NAND2X1 g7471__6783 (.A(n_97),
	.B(n_98),
	.Y(n_151));
   NAND2X1 g7472__3680 (.A(n_95),
	.B(n_96),
	.Y(n_150));
   NAND2X1 g7473__1617 (.A(n_91),
	.B(n_94),
	.Y(n_149));
   NAND2X1 g7474__2802 (.A(n_92),
	.B(n_93),
	.Y(n_148));
   NAND2X1 g7475__1705 (.A(n_89),
	.B(n_90),
	.Y(n_147));
   NAND2X1 g7476__5122 (.A(n_87),
	.B(n_88),
	.Y(n_146));
   NAND2X1 g7477__8246 (.A(n_85),
	.B(n_86),
	.Y(n_145));
   NAND2X1 g7478__7098 (.A(n_83),
	.B(n_84),
	.Y(n_144));
   NAND2X1 g7479__6131 (.A(n_81),
	.B(n_82),
	.Y(n_143));
   NAND2X1 g7480__1881 (.A(n_79),
	.B(n_80),
	.Y(n_142));
   NAND2X1 g7481__5115 (.A(n_139),
	.B(n_78),
	.Y(n_141));
   OAI211X1 g7482__7482 (.A0(reg_curr_val[0]),
	.A1(n_73),
	.B0(n_41),
	.C0(n_77),
	.Y(n_140));
   AOI22X1 g7483__4733 (.A0(n_206),
	.A1(n_74),
	.B0(reg_curr_val[21]),
	.B1(n_35),
	.Y(n_139));
   AOI22X1 g7484__6161 (.A0(n_207),
	.A1(n_74),
	.B0(reg_curr_val[22]),
	.B1(n_35),
	.Y(n_138));
   AOI22X1 g7485__9315 (.A0(reg_reload_val[22]),
	.A1(n_75),
	.B0(PWDATA[22]),
	.B1(FE_OFN2_n),
	.Y(n_137));
   AOI22X1 g7486__9945 (.A0(reg_reload_val[23]),
	.A1(n_75),
	.B0(PWDATA[23]),
	.B1(n_0),
	.Y(n_136));
   AOI22X1 g7487__2883 (.A0(n_208),
	.A1(n_74),
	.B0(reg_curr_val[23]),
	.B1(n_35),
	.Y(n_135));
   AOI22X1 g7488__2346 (.A0(reg_reload_val[24]),
	.A1(n_75),
	.B0(PWDATA[24]),
	.B1(FE_OFN2_n),
	.Y(n_134));
   AOI22X1 g7489__1666 (.A0(n_209),
	.A1(n_74),
	.B0(reg_curr_val[24]),
	.B1(n_35),
	.Y(n_133));
   AOI22X1 g7490__7410 (.A0(reg_reload_val[25]),
	.A1(n_75),
	.B0(PWDATA[25]),
	.B1(n_0),
	.Y(n_132));
   AOI22X1 g7491__6417 (.A0(n_210),
	.A1(n_74),
	.B0(reg_curr_val[25]),
	.B1(n_35),
	.Y(n_131));
   AOI22X1 g7492__5477 (.A0(reg_reload_val[26]),
	.A1(n_75),
	.B0(PWDATA[26]),
	.B1(FE_OFN2_n),
	.Y(n_130));
   AOI22X1 g7493__2398 (.A0(n_211),
	.A1(n_74),
	.B0(reg_curr_val[26]),
	.B1(n_35),
	.Y(n_129));
   AOI22X1 g7494__5107 (.A0(reg_reload_val[27]),
	.A1(n_75),
	.B0(PWDATA[27]),
	.B1(FE_OFN2_n),
	.Y(n_128));
   AOI22X1 g7495__6260 (.A0(n_212),
	.A1(n_74),
	.B0(reg_curr_val[27]),
	.B1(n_35),
	.Y(n_127));
   AOI22X1 g7496__4319 (.A0(reg_reload_val[28]),
	.A1(n_75),
	.B0(PWDATA[28]),
	.B1(FE_OFN2_n),
	.Y(n_126));
   AOI22X1 g7497__8428 (.A0(n_213),
	.A1(n_74),
	.B0(reg_curr_val[28]),
	.B1(n_35),
	.Y(n_125));
   AOI22X1 g7498__5526 (.A0(reg_reload_val[29]),
	.A1(n_75),
	.B0(PWDATA[29]),
	.B1(FE_OFN2_n),
	.Y(n_124));
   AOI22X1 g7499__6783 (.A0(reg_reload_val[30]),
	.A1(n_75),
	.B0(PWDATA[30]),
	.B1(FE_OFN2_n),
	.Y(n_123));
   AOI22X1 g7500__3680 (.A0(n_215),
	.A1(n_74),
	.B0(reg_curr_val[30]),
	.B1(n_35),
	.Y(n_122));
   AOI22X1 g7501__1617 (.A0(n_214),
	.A1(n_74),
	.B0(reg_curr_val[29]),
	.B1(n_35),
	.Y(n_121));
   AOI22X1 g7502__2802 (.A0(reg_reload_val[31]),
	.A1(n_75),
	.B0(PWDATA[31]),
	.B1(FE_OFN2_n),
	.Y(n_120));
   AOI22X1 g7503__1705 (.A0(n_216),
	.A1(n_74),
	.B0(reg_curr_val[31]),
	.B1(n_35),
	.Y(n_119));
   AOI22X1 g7504__5122 (.A0(reg_reload_val[1]),
	.A1(n_75),
	.B0(PWDATA[1]),
	.B1(n_0),
	.Y(n_118));
   AOI22X1 g7505__8246 (.A0(n_186),
	.A1(n_74),
	.B0(reg_curr_val[1]),
	.B1(n_35),
	.Y(n_117));
   AOI22X1 g7506__7098 (.A0(reg_reload_val[2]),
	.A1(n_75),
	.B0(PWDATA[2]),
	.B1(n_0),
	.Y(n_116));
   AOI22X1 g7507__6131 (.A0(n_187),
	.A1(n_74),
	.B0(reg_curr_val[2]),
	.B1(n_35),
	.Y(n_115));
   AOI22X1 g7508__1881 (.A0(reg_reload_val[3]),
	.A1(n_75),
	.B0(PWDATA[3]),
	.B1(n_0),
	.Y(n_114));
   AOI22X1 g7509__5115 (.A0(n_188),
	.A1(n_74),
	.B0(reg_curr_val[3]),
	.B1(n_35),
	.Y(n_113));
   AOI22X1 g7510__7482 (.A0(reg_reload_val[4]),
	.A1(n_75),
	.B0(PWDATA[4]),
	.B1(n_0),
	.Y(n_112));
   AOI22X1 g7511__4733 (.A0(n_189),
	.A1(n_74),
	.B0(reg_curr_val[4]),
	.B1(n_35),
	.Y(n_111));
   AOI22X1 g7512__6161 (.A0(reg_reload_val[5]),
	.A1(n_75),
	.B0(PWDATA[5]),
	.B1(n_0),
	.Y(n_110));
   AOI22X1 g7513__9315 (.A0(n_190),
	.A1(n_74),
	.B0(reg_curr_val[5]),
	.B1(n_35),
	.Y(n_109));
   AOI22X1 g7514__9945 (.A0(n_191),
	.A1(n_74),
	.B0(reg_curr_val[6]),
	.B1(n_35),
	.Y(n_108));
   AOI22X1 g7515__2883 (.A0(reg_reload_val[6]),
	.A1(n_75),
	.B0(PWDATA[6]),
	.B1(FE_OFN2_n),
	.Y(n_107));
   AOI22X1 g7516__2346 (.A0(reg_reload_val[7]),
	.A1(n_75),
	.B0(PWDATA[7]),
	.B1(FE_OFN2_n),
	.Y(n_106));
   AOI22X1 g7517__1666 (.A0(n_192),
	.A1(n_74),
	.B0(reg_curr_val[7]),
	.B1(n_35),
	.Y(n_105));
   AOI22X1 g7518__7410 (.A0(reg_reload_val[8]),
	.A1(n_75),
	.B0(PWDATA[8]),
	.B1(FE_OFN2_n),
	.Y(n_104));
   AOI22X1 g7519__6417 (.A0(n_193),
	.A1(n_74),
	.B0(reg_curr_val[8]),
	.B1(n_35),
	.Y(n_103));
   AOI22X1 g7520__5477 (.A0(reg_reload_val[9]),
	.A1(n_75),
	.B0(PWDATA[9]),
	.B1(FE_OFN2_n),
	.Y(n_102));
   AOI22X1 g7521__2398 (.A0(n_194),
	.A1(n_74),
	.B0(reg_curr_val[9]),
	.B1(n_35),
	.Y(n_101));
   AOI22X1 g7522__5107 (.A0(reg_reload_val[10]),
	.A1(n_75),
	.B0(PWDATA[10]),
	.B1(FE_OFN2_n),
	.Y(n_100));
   AOI22X1 g7523__6260 (.A0(n_195),
	.A1(n_74),
	.B0(reg_curr_val[10]),
	.B1(n_35),
	.Y(n_99));
   AOI22X1 g7524__4319 (.A0(reg_reload_val[11]),
	.A1(n_75),
	.B0(PWDATA[11]),
	.B1(FE_OFN2_n),
	.Y(n_98));
   AOI22X1 g7525__8428 (.A0(n_196),
	.A1(n_74),
	.B0(reg_curr_val[11]),
	.B1(n_35),
	.Y(n_97));
   AOI22X1 g7526__5526 (.A0(reg_reload_val[12]),
	.A1(n_75),
	.B0(PWDATA[12]),
	.B1(FE_OFN2_n),
	.Y(n_96));
   AOI22X1 g7527__6783 (.A0(n_197),
	.A1(n_74),
	.B0(reg_curr_val[12]),
	.B1(n_35),
	.Y(n_95));
   AOI22X1 g7528__3680 (.A0(reg_reload_val[13]),
	.A1(n_75),
	.B0(PWDATA[13]),
	.B1(FE_OFN2_n),
	.Y(n_94));
   AOI22X1 g7529__1617 (.A0(reg_reload_val[14]),
	.A1(n_75),
	.B0(PWDATA[14]),
	.B1(FE_OFN2_n),
	.Y(n_93));
   AOI22X1 g7530__2802 (.A0(n_199),
	.A1(n_74),
	.B0(reg_curr_val[14]),
	.B1(n_35),
	.Y(n_92));
   AOI22X1 g7531__1705 (.A0(n_198),
	.A1(n_74),
	.B0(reg_curr_val[13]),
	.B1(n_35),
	.Y(n_91));
   AOI22X1 g7532__5122 (.A0(reg_reload_val[15]),
	.A1(n_75),
	.B0(PWDATA[15]),
	.B1(n_0),
	.Y(n_90));
   AOI22X1 g7533__8246 (.A0(n_200),
	.A1(n_74),
	.B0(reg_curr_val[15]),
	.B1(n_35),
	.Y(n_89));
   AOI22X1 g7534__7098 (.A0(reg_reload_val[16]),
	.A1(n_75),
	.B0(PWDATA[16]),
	.B1(FE_OFN2_n),
	.Y(n_88));
   AOI22X1 g7535__6131 (.A0(n_201),
	.A1(n_74),
	.B0(reg_curr_val[16]),
	.B1(n_35),
	.Y(n_87));
   AOI22X1 g7536__1881 (.A0(reg_reload_val[17]),
	.A1(n_75),
	.B0(PWDATA[17]),
	.B1(FE_OFN2_n),
	.Y(n_86));
   AOI22X1 g7537__5115 (.A0(n_202),
	.A1(n_74),
	.B0(reg_curr_val[17]),
	.B1(n_35),
	.Y(n_85));
   AOI22X1 g7538__7482 (.A0(reg_reload_val[18]),
	.A1(n_75),
	.B0(PWDATA[18]),
	.B1(FE_OFN2_n),
	.Y(n_84));
   AOI22X1 g7539__4733 (.A0(n_203),
	.A1(n_74),
	.B0(reg_curr_val[18]),
	.B1(n_35),
	.Y(n_83));
   AOI22X1 g7540__6161 (.A0(reg_reload_val[19]),
	.A1(n_75),
	.B0(PWDATA[19]),
	.B1(FE_OFN2_n),
	.Y(n_82));
   AOI22X1 g7541__9315 (.A0(n_204),
	.A1(n_74),
	.B0(reg_curr_val[19]),
	.B1(n_35),
	.Y(n_81));
   AOI22X1 g7542__9945 (.A0(reg_reload_val[20]),
	.A1(n_75),
	.B0(PWDATA[20]),
	.B1(FE_OFN2_n),
	.Y(n_80));
   AOI22X1 g7543__2883 (.A0(n_205),
	.A1(n_74),
	.B0(reg_curr_val[20]),
	.B1(n_35),
	.Y(n_79));
   AOI22X1 g7544__2346 (.A0(reg_reload_val[21]),
	.A1(n_75),
	.B0(PWDATA[21]),
	.B1(FE_OFN2_n),
	.Y(n_78));
   NAND2X1 g7545__1666 (.A(reg_reload_val[0]),
	.B(n_75),
	.Y(n_77));
   NAND2BX1 g7546__7410 (.AN(n_72),
	.B(n_33),
	.Y(n_76));
   INVX1 g7547 (.A(n_74),
	.Y(n_73));
   AND3X2 g7548__6417 (.A(n_31),
	.B(n_34),
	.C(n_71),
	.Y(n_75));
   AND3X2 g7549__5477 (.A(n_31),
	.B(n_34),
	.C(n_70),
	.Y(n_74));
   AND4XL g7550__2398 (.A(reg_ctrl[3]),
	.B(reg_curr_val[0]),
	.C(n_28),
	.D(n_302),
	.Y(n_72));
   INVX1 g7551 (.A(n_70),
	.Y(n_71));
   NAND2BX1 g7552__5107 (.AN(reg_curr_val[0]),
	.B(n_302),
	.Y(n_70));
   OR4X1 g7555__8428 (.A(reg_curr_val[30]),
	.B(reg_curr_val[28]),
	.C(reg_curr_val[29]),
	.D(n_66),
	.Y(n_67));
   OR4X1 g7556__5526 (.A(reg_curr_val[20]),
	.B(reg_curr_val[27]),
	.C(reg_curr_val[26]),
	.D(n_65),
	.Y(n_66));
   OR4X1 g7557__6783 (.A(reg_curr_val[22]),
	.B(reg_curr_val[21]),
	.C(reg_curr_val[23]),
	.D(n_64),
	.Y(n_65));
   OR4X1 g7558__3680 (.A(reg_curr_val[4]),
	.B(reg_curr_val[14]),
	.C(reg_curr_val[15]),
	.D(n_63),
	.Y(n_64));
   OR4X1 g7559__1617 (.A(reg_curr_val[25]),
	.B(reg_curr_val[31]),
	.C(reg_curr_val[24]),
	.D(n_62),
	.Y(n_63));
   OR4X1 g7562__2802 (.A(reg_curr_val[18]),
	.B(reg_curr_val[16]),
	.C(reg_curr_val[17]),
	.D(n_53),
	.Y(n_62));
   NAND3XL g7567__1705 (.A(n_15),
	.B(n_44),
	.C(n_49),
	.Y(n_61));
   OAI211XL g7568__5122 (.A0(n_9),
	.A1(n_43),
	.B0(n_26),
	.C0(n_50),
	.Y(n_60));
   NAND3XL g7569__8246 (.A(n_12),
	.B(n_44),
	.C(n_51),
	.Y(n_59));
   OAI211XL g7571__7098 (.A0(PADDR[2]),
	.A1(n_45),
	.B0(n_24),
	.C0(n_47),
	.Y(n_58));
   OAI211XL g7573__6131 (.A0(PADDR[2]),
	.A1(n_43),
	.B0(n_23),
	.C0(n_14),
	.Y(n_57));
   OAI221X1 g7574__1881 (.A0(n_10),
	.A1(n_6),
	.B0(n_3),
	.B1(n_185),
	.C0(n_52),
	.Y(n_56));
   OAI211XL g7575__5115 (.A0(n_182),
	.A1(n_45),
	.B0(n_39),
	.C0(n_13),
	.Y(n_55));
   NAND2X1 g7576__7482 (.A(n_44),
	.B(n_46),
	.Y(n_54));
   OR4X1 g7577__4733 (.A(reg_curr_val[13]),
	.B(reg_curr_val[19]),
	.C(reg_curr_val[12]),
	.D(n_37),
	.Y(n_53));
   AOI222X1 g7578__6161 (.A0(reg_ctrl[0]),
	.A1(n_19),
	.B0(n_17),
	.B1(n_40),
	.C0(read_mux_byte0_reg[0]),
	.C1(read_enable),
	.Y(n_52));
   AOI2BB2X1 g7579__9315 (.A0N(PADDR[3]),
	.A1N(n_43),
	.B0(ECOREVNUM[1]),
	.B1(n_1),
	.Y(n_51));
   AOI21XL g7580__9945 (.A0(read_mux_byte0_reg[3]),
	.A1(read_enable),
	.B0(n_48),
	.Y(n_50));
   AOI22XL g7581__2883 (.A0(PADDR[3]),
	.A1(n_42),
	.B0(ECOREVNUM[0]),
	.B1(n_1),
	.Y(n_49));
   NOR2XL g7582__2346 (.A(n_8),
	.B(n_45),
	.Y(n_48));
   AOI222X1 g7583__1666 (.A0(PADDR[4]),
	.A1(n_38),
	.B0(reg_reload_val[2]),
	.B1(FE_OFN3_n_4),
	.C0(read_mux_byte0_reg[2]),
	.C1(read_enable),
	.Y(n_47));
   AOI222X1 g7584__7410 (.A0(reg_reload_val[7]),
	.A1(n_4),
	.B0(ECOREVNUM[3]),
	.B1(n_1),
	.C0(read_mux_byte0_reg[7]),
	.C1(read_enable),
	.Y(n_46));
   INVX1 g7605 (.A(n_43),
	.Y(n_42));
   AOI22X1 g7606__6417 (.A0(reg_curr_val[0]),
	.A1(n_35),
	.B0(PWDATA[0]),
	.B1(n_0),
	.Y(n_41));
   NAND2X1 g7623__5477 (.A(PADDR[4]),
	.B(n_40),
	.Y(n_45));
   NAND2X1 g7624__2398 (.A(PADDR[2]),
	.B(n_40),
	.Y(n_44));
   NAND2BX1 g7625__5107 (.AN(PADDR[4]),
	.B(n_40),
	.Y(n_43));
   NAND2X1 g7626__6260 (.A(ECOREVNUM[2]),
	.B(n_1),
	.Y(n_39));
   AND2X1 g7627__4319 (.A(PADDR[5]),
	.B(n_36),
	.Y(n_40));
   AND2X1 g7628__8428 (.A(n_9),
	.B(n_36),
	.Y(n_38));
   OR4X1 g7629__5526 (.A(reg_curr_val[7]),
	.B(reg_curr_val[6]),
	.C(reg_curr_val[5]),
	.D(n_20),
	.Y(n_37));
   INVX1 g7633 (.A(n_35),
	.Y(n_34));
   NAND3BXL g7634__6783 (.AN(n_10),
	.B(PWDATA[0]),
	.C(n_22),
	.Y(n_33));
   NOR2XL g7635__3680 (.A(n_25),
	.B(n_29),
	.Y(n_36));
   AND2X2 g7637__1617 (.A(n_27),
	.B(n_31),
	.Y(n_35));
   NAND2X1 g7639__2802 (.A(n_9),
	.B(n_22),
	.Y(n_32));
   AND2X4 g7641__1705 (.A(n_179),
	.B(n_22),
	.Y(n_30));
   INVX1 g7642 (.A(n_27),
	.Y(n_28));
   AOI22XL g7643__5122 (.A0(reg_ctrl[3]),
	.A1(n_19),
	.B0(reg_reload_val[3]),
	.B1(FE_OFN3_n_4),
	.Y(n_26));
   NAND4BX1 g7644__8246 (.AN(read_enable),
	.B(PADDR[7]),
	.C(PADDR[6]),
	.D(n_11),
	.Y(n_29));
   NAND2X1 g7645__7098 (.A(reg_ctrl[0]),
	.B(n_21),
	.Y(n_27));
   NAND2X1 g7647__6131 (.A(reg_ctrl[2]),
	.B(n_19),
	.Y(n_24));
   NAND2X1 g7648__1881 (.A(reg_ctrl[1]),
	.B(n_19),
	.Y(n_23));
   NOR3BXL g7649__5115 (.AN(PADDR[5]),
	.B(n_10),
	.C(PADDR[4]),
	.Y(n_25));
   AOI22X1 g7650__7482 (.A0(reg_ctrl[2]),
	.A1(n_7),
	.B0(reg_ctrl[1]),
	.B1(n_2),
	.Y(n_21));
   OR4X1 g7651__4733 (.A(reg_curr_val[11]),
	.B(reg_curr_val[10]),
	.C(reg_curr_val[8]),
	.D(reg_curr_val[9]),
	.Y(n_20));
   AND2X1 g7652__6161 (.A(PSEL),
	.B(n_16),
	.Y(n_22));
   AO21X1 g7653__9315 (.A0(PADDR[4]),
	.A1(n_5),
	.B0(PADDR[3]),
	.Y(n_17));
   NOR3BX1 g7654__9945 (.AN(PWRITE),
	.B(PENABLE),
	.C(n_183),
	.Y(n_16));
   NOR2XL g7655__2883 (.A(n_8),
	.B(n_184),
	.Y(n_19));
   NOR3X1 g7656__2346 (.A(reg_ctrl[2]),
	.B(reg_ctrl[1]),
	.C(PSEL),
	.Y(n_18));
   AOI22XL g7657__1666 (.A0(reg_reload_val[4]),
	.A1(FE_OFN3_n_4),
	.B0(read_mux_byte0_reg[4]),
	.B1(read_enable),
	.Y(n_15));
   AOI22XL g7658__7410 (.A0(reg_reload_val[1]),
	.A1(FE_OFN3_n_4),
	.B0(read_mux_byte0_reg[1]),
	.B1(read_enable),
	.Y(n_14));
   AOI22XL g7659__6417 (.A0(reg_reload_val[6]),
	.A1(n_4),
	.B0(read_mux_byte0_reg[6]),
	.B1(read_enable),
	.Y(n_13));
   AOI22XL g7660__5477 (.A0(reg_reload_val[5]),
	.A1(FE_OFN3_n_4),
	.B0(read_mux_byte0_reg[5]),
	.B1(read_enable),
	.Y(n_12));
   AND4XL g7661__2398 (.A(PADDR[8]),
	.B(PADDR[10]),
	.C(PADDR[11]),
	.D(PADDR[9]),
	.Y(n_11));
   INVX1 g7662 (.A(n_9),
	.Y(n_8));
   NAND2X1 g7663__5107 (.A(PADDR[3]),
	.B(PADDR[2]),
	.Y(n_10));
   NOR2XL g7664__6260 (.A(PADDR[3]),
	.B(PADDR[2]),
	.Y(n_9));
   NAND2BX1 g7665__4319 (.AN(ext_in_delay),
	.B(ext_in_sync2),
	.Y(n_7));
   NAND2BX1 g7666__8428 (.AN(n_184),
	.B(TIMERINT),
	.Y(n_6));
   INVX1 g7669 (.A(PADDR[2]),
	.Y(n_5));
   SDFFRXL ext_in_sync2_reg (.CK(PCLK),
	.D(ext_in_sync1),
	.Q(ext_in_sync2),
	.QN(n_2),
	.RN(PRESETn),
	.SE(n_18),
	.SI(ext_in_sync2));
   SDFFRXL \reg_reload_val_reg[0]  (.CK(PCLKG),
	.D(reg_reload_val[0]),
	.Q(reg_reload_val[0]),
	.QN(n_3),
	.RN(PRESETn),
	.SE(n_30),
	.SI(PWDATA[0]));
   NOR2BX1 g4492__5526 (.AN(n_25),
	.B(n_29),
	.Y(n_1));
   NOR2BX1 g7676__6783 (.AN(n_22),
	.B(n_182),
	.Y(n_0));
   XOR2X1 dec_sub_440_29_g600__3680 (.A(reg_curr_val[19]),
	.B(dec_sub_440_29_n_325),
	.Y(n_204));
   XOR2X1 dec_sub_440_29_g601__1617 (.A(reg_curr_val[31]),
	.B(dec_sub_440_29_n_338),
	.Y(n_216));
   XOR2X1 dec_sub_440_29_g602__2802 (.A(reg_curr_val[11]),
	.B(dec_sub_440_29_n_335),
	.Y(n_196));
   AO21X1 dec_sub_440_29_g603__1705 (.A0(reg_curr_val[18]),
	.A1(dec_sub_440_29_n_358),
	.B0(dec_sub_440_29_n_325),
	.Y(n_203));
   XOR2X1 dec_sub_440_29_g604__5122 (.A(reg_curr_val[29]),
	.B(dec_sub_440_29_n_357),
	.Y(n_214));
   XOR2X1 dec_sub_440_29_g605__8246 (.A(reg_curr_val[27]),
	.B(dec_sub_440_29_n_354),
	.Y(n_212));
   NOR2XL dec_sub_440_29_g606__7098 (.A(reg_curr_val[18]),
	.B(dec_sub_440_29_n_358),
	.Y(dec_sub_440_29_n_325));
   AO21X1 dec_sub_440_29_g607__6131 (.A0(reg_curr_val[10]),
	.A1(dec_sub_440_29_n_373),
	.B0(dec_sub_440_29_n_335),
	.Y(n_195));
   AO21X1 dec_sub_440_29_g608__1881 (.A0(reg_curr_val[30]),
	.A1(dec_sub_440_29_n_349),
	.B0(dec_sub_440_29_n_338),
	.Y(n_215));
   XOR2X1 dec_sub_440_29_g609__5115 (.A(reg_curr_val[25]),
	.B(dec_sub_440_29_n_376),
	.Y(n_210));
   XOR2X1 dec_sub_440_29_g610__7482 (.A(reg_curr_val[23]),
	.B(dec_sub_440_29_n_370),
	.Y(n_208));
   NOR2XL dec_sub_440_29_g611__4733 (.A(reg_curr_val[10]),
	.B(dec_sub_440_29_n_373),
	.Y(dec_sub_440_29_n_335));
   NOR2XL dec_sub_440_29_g612__6161 (.A(reg_curr_val[30]),
	.B(dec_sub_440_29_n_349),
	.Y(dec_sub_440_29_n_338));
   XOR2X1 dec_sub_440_29_g613__9315 (.A(reg_curr_val[21]),
	.B(dec_sub_440_29_n_388),
	.Y(n_206));
   XOR2X1 dec_sub_440_29_g614__9945 (.A(reg_curr_val[15]),
	.B(dec_sub_440_29_n_390),
	.Y(n_200));
   AO21X1 dec_sub_440_29_g615__2883 (.A0(reg_curr_val[28]),
	.A1(dec_sub_440_29_n_382),
	.B0(dec_sub_440_29_n_357),
	.Y(n_213));
   AO21X1 dec_sub_440_29_g616__2346 (.A0(reg_curr_val[26]),
	.A1(dec_sub_440_29_n_368),
	.B0(dec_sub_440_29_n_354),
	.Y(n_211));
   OAI2BB1X1 dec_sub_440_29_g617__1666 (.A0N(reg_curr_val[17]),
	.A1N(dec_sub_440_29_n_404),
	.B0(dec_sub_440_29_n_358),
	.Y(n_202));
   OR3X1 dec_sub_440_29_g618__7410 (.A(reg_curr_val[28]),
	.B(reg_curr_val[29]),
	.C(dec_sub_440_29_n_382),
	.Y(dec_sub_440_29_n_349));
   XOR2X1 dec_sub_440_29_g619__6417 (.A(reg_curr_val[13]),
	.B(dec_sub_440_29_n_402),
	.Y(n_198));
   NOR2XL dec_sub_440_29_g620__5477 (.A(reg_curr_val[26]),
	.B(dec_sub_440_29_n_368),
	.Y(dec_sub_440_29_n_354));
   NOR2XL dec_sub_440_29_g621__2398 (.A(reg_curr_val[28]),
	.B(dec_sub_440_29_n_382),
	.Y(dec_sub_440_29_n_357));
   OR2X1 dec_sub_440_29_g622__5107 (.A(reg_curr_val[17]),
	.B(dec_sub_440_29_n_404),
	.Y(dec_sub_440_29_n_358));
   AO21X1 dec_sub_440_29_g623__6260 (.A0(reg_curr_val[22]),
	.A1(dec_sub_440_29_n_386),
	.B0(dec_sub_440_29_n_370),
	.Y(n_207));
   AO21X1 dec_sub_440_29_g624__4319 (.A0(reg_curr_val[24]),
	.A1(dec_sub_440_29_n_396),
	.B0(dec_sub_440_29_n_376),
	.Y(n_209));
   OAI2BB1X1 dec_sub_440_29_g625__8428 (.A0N(reg_curr_val[9]),
	.A1N(dec_sub_440_29_n_412),
	.B0(dec_sub_440_29_n_373),
	.Y(n_194));
   XOR2X1 dec_sub_440_29_g626__5526 (.A(reg_curr_val[7]),
	.B(dec_sub_440_29_n_409),
	.Y(n_192));
   NAND2BX1 dec_sub_440_29_g627__6783 (.AN(dec_sub_440_29_n_396),
	.B(dec_sub_440_29_n_447),
	.Y(dec_sub_440_29_n_368));
   NOR2XL dec_sub_440_29_g628__3680 (.A(reg_curr_val[22]),
	.B(dec_sub_440_29_n_386),
	.Y(dec_sub_440_29_n_370));
   OR2X1 dec_sub_440_29_g629__1617 (.A(reg_curr_val[9]),
	.B(dec_sub_440_29_n_412),
	.Y(dec_sub_440_29_n_373));
   NOR2XL dec_sub_440_29_g630__2802 (.A(reg_curr_val[24]),
	.B(dec_sub_440_29_n_396),
	.Y(dec_sub_440_29_n_376));
   AO21X1 dec_sub_440_29_g631__1705 (.A0(reg_curr_val[20]),
	.A1(dec_sub_440_29_n_398),
	.B0(dec_sub_440_29_n_388),
	.Y(n_205));
   AO21X1 dec_sub_440_29_g632__5122 (.A0(reg_curr_val[14]),
	.A1(dec_sub_440_29_n_400),
	.B0(dec_sub_440_29_n_390),
	.Y(n_199));
   OR4X1 dec_sub_440_29_g633__8246 (.A(reg_curr_val[26]),
	.B(reg_curr_val[27]),
	.C(dec_sub_440_29_n_446),
	.D(dec_sub_440_29_n_396),
	.Y(dec_sub_440_29_n_382));
   XOR2X1 dec_sub_440_29_g634__7098 (.A(reg_curr_val[5]),
	.B(dec_sub_440_29_n_421),
	.Y(n_190));
   NAND2BX1 dec_sub_440_29_g635__6131 (.AN(dec_sub_440_29_n_398),
	.B(dec_sub_440_29_n_455),
	.Y(dec_sub_440_29_n_386));
   NOR2XL dec_sub_440_29_g636__1881 (.A(reg_curr_val[20]),
	.B(dec_sub_440_29_n_398),
	.Y(dec_sub_440_29_n_388));
   NOR2XL dec_sub_440_29_g637__5115 (.A(reg_curr_val[14]),
	.B(dec_sub_440_29_n_400),
	.Y(dec_sub_440_29_n_390));
   AO21X1 dec_sub_440_29_g638__7482 (.A0(reg_curr_val[12]),
	.A1(dec_sub_440_29_n_415),
	.B0(dec_sub_440_29_n_402),
	.Y(n_197));
   OAI2BB1X1 dec_sub_440_29_g639__4733 (.A0N(reg_curr_val[16]),
	.A1N(dec_sub_440_29_n_418),
	.B0(dec_sub_440_29_n_404),
	.Y(n_201));
   OR4X1 dec_sub_440_29_g640__6161 (.A(reg_curr_val[23]),
	.B(reg_curr_val[22]),
	.C(dec_sub_440_29_n_454),
	.D(dec_sub_440_29_n_398),
	.Y(dec_sub_440_29_n_396));
   NAND2BX1 dec_sub_440_29_g641__9315 (.AN(dec_sub_440_29_n_418),
	.B(dec_sub_440_29_n_443),
	.Y(dec_sub_440_29_n_398));
   NAND2BX1 dec_sub_440_29_g642__9945 (.AN(dec_sub_440_29_n_415),
	.B(dec_sub_440_29_n_452),
	.Y(dec_sub_440_29_n_400));
   NOR2XL dec_sub_440_29_g643__2883 (.A(reg_curr_val[12]),
	.B(dec_sub_440_29_n_415),
	.Y(dec_sub_440_29_n_402));
   OR2X1 dec_sub_440_29_g644__2346 (.A(reg_curr_val[16]),
	.B(dec_sub_440_29_n_418),
	.Y(dec_sub_440_29_n_404));
   OAI2BB1X1 dec_sub_440_29_g645__1666 (.A0N(reg_curr_val[8]),
	.A1N(dec_sub_440_29_n_424),
	.B0(dec_sub_440_29_n_412),
	.Y(n_193));
   AO21X1 dec_sub_440_29_g646__7410 (.A0(reg_curr_val[6]),
	.A1(dec_sub_440_29_n_420),
	.B0(dec_sub_440_29_n_409),
	.Y(n_191));
   NOR2XL dec_sub_440_29_g647__6417 (.A(reg_curr_val[6]),
	.B(dec_sub_440_29_n_420),
	.Y(dec_sub_440_29_n_409));
   OR2X1 dec_sub_440_29_g648__5477 (.A(reg_curr_val[8]),
	.B(dec_sub_440_29_n_424),
	.Y(dec_sub_440_29_n_412));
   NAND2BX1 dec_sub_440_29_g649__2398 (.AN(dec_sub_440_29_n_424),
	.B(dec_sub_440_29_n_441),
	.Y(dec_sub_440_29_n_415));
   AO21X1 dec_sub_440_29_g650__5107 (.A0(reg_curr_val[4]),
	.A1(dec_sub_440_29_n_426),
	.B0(dec_sub_440_29_n_421),
	.Y(n_189));
   OR4X1 dec_sub_440_29_g651__6260 (.A(reg_curr_val[14]),
	.B(reg_curr_val[15]),
	.C(dec_sub_440_29_n_437),
	.D(dec_sub_440_29_n_424),
	.Y(dec_sub_440_29_n_418));
   NAND2X1 dec_sub_440_29_g652__4319 (.A(dec_sub_440_29_n_450),
	.B(dec_sub_440_29_n_429),
	.Y(dec_sub_440_29_n_420));
   NOR2XL dec_sub_440_29_g653__8428 (.A(reg_curr_val[4]),
	.B(dec_sub_440_29_n_426),
	.Y(dec_sub_440_29_n_421));
   OR4X1 dec_sub_440_29_g654__5526 (.A(reg_curr_val[6]),
	.B(reg_curr_val[7]),
	.C(dec_sub_440_29_n_449),
	.D(dec_sub_440_29_n_426),
	.Y(dec_sub_440_29_n_424));
   INVX1 dec_sub_440_29_g655 (.A(dec_sub_440_29_n_429),
	.Y(dec_sub_440_29_n_426));
   AO21X1 dec_sub_440_29_g656__6783 (.A0(reg_curr_val[3]),
	.A1(dec_sub_440_29_n_434),
	.B0(dec_sub_440_29_n_429),
	.Y(n_188));
   NOR2XL dec_sub_440_29_g657__3680 (.A(reg_curr_val[3]),
	.B(dec_sub_440_29_n_434),
	.Y(dec_sub_440_29_n_429));
   OAI2BB1X1 dec_sub_440_29_g658__1617 (.A0N(reg_curr_val[2]),
	.A1N(dec_sub_440_29_n_457),
	.B0(dec_sub_440_29_n_434),
	.Y(n_187));
   OR2X1 dec_sub_440_29_g659__2802 (.A(reg_curr_val[2]),
	.B(dec_sub_440_29_n_457),
	.Y(dec_sub_440_29_n_434));
   NAND2X1 dec_sub_440_29_g660__1705 (.A(dec_sub_440_29_n_452),
	.B(dec_sub_440_29_n_441),
	.Y(dec_sub_440_29_n_437));
   NOR4XL dec_sub_440_29_g661__5122 (.A(reg_curr_val[10]),
	.B(reg_curr_val[9]),
	.C(reg_curr_val[8]),
	.D(reg_curr_val[11]),
	.Y(dec_sub_440_29_n_441));
   NOR4XL dec_sub_440_29_g662__8246 (.A(reg_curr_val[16]),
	.B(reg_curr_val[17]),
	.C(reg_curr_val[19]),
	.D(reg_curr_val[18]),
	.Y(dec_sub_440_29_n_443));
   OAI2BB1X1 dec_sub_440_29_g663__7098 (.A0N(reg_curr_val[0]),
	.A1N(reg_curr_val[1]),
	.B0(dec_sub_440_29_n_457),
	.Y(n_186));
   INVX1 dec_sub_440_29_g664 (.A(dec_sub_440_29_n_447),
	.Y(dec_sub_440_29_n_446));
   NOR2XL dec_sub_440_29_g665__6131 (.A(reg_curr_val[25]),
	.B(reg_curr_val[24]),
	.Y(dec_sub_440_29_n_447));
   INVX1 dec_sub_440_29_g666 (.A(dec_sub_440_29_n_450),
	.Y(dec_sub_440_29_n_449));
   NOR2XL dec_sub_440_29_g667__1881 (.A(reg_curr_val[5]),
	.B(reg_curr_val[4]),
	.Y(dec_sub_440_29_n_450));
   NOR2XL dec_sub_440_29_g668__5115 (.A(reg_curr_val[13]),
	.B(reg_curr_val[12]),
	.Y(dec_sub_440_29_n_452));
   INVX1 dec_sub_440_29_g669 (.A(dec_sub_440_29_n_455),
	.Y(dec_sub_440_29_n_454));
   NOR2XL dec_sub_440_29_g670__7482 (.A(reg_curr_val[21]),
	.B(reg_curr_val[20]),
	.Y(dec_sub_440_29_n_455));
   OR2X1 dec_sub_440_29_g671__4733 (.A(reg_curr_val[1]),
	.B(reg_curr_val[0]),
	.Y(dec_sub_440_29_n_457));
   NOR4XL g2 (.A(reg_curr_val[3]),
	.B(n_67),
	.C(reg_curr_val[1]),
	.D(reg_curr_val[2]),
	.Y(n_302));
endmodule

